### ISSUE TITLE
Verify context of macros

### ISSUE THREAD

**Issue by goderbauer** [jakemac53/macro_prototype#21]
Some macros may only make sense in a given context. For example, the field macro defined in https://github.com/jakemac53/macro_prototype/pull/20 only makes sense on fields within a RenderObject class because the generated code calls methods from that class. 

However, currently, there doesn't appear to be a mechanism to verify that the macro annotation is used in the correct context and instead of giving a good error message, broken code is generated if the macro is used in fields in other subclasses.

**Comment by jakemac53** [comment]
The most straightforward solution here is going to be giving access to the class from the field/method declarations. But you would only get the previous phases information.

So for instance in the declaration phase you would be able to do subtype checks on the parent class (which is what you need here), but you wouldn't be able to look at the _members_ of that class, because they are being generated still (in the current phase).

Once in the definition phase though you would have access to all the members of the parent class.

**Comment by jakemac53** [comment]
Actually I noticed we already provide this for Method macros, it was just an oversight to not include it for Field macros, so I will add that.

**Comment by jakemac53** [comment]
This should all be there now, see the `definingClass` getters on fields/methods.
