### ISSUE TITLE
ClassDefinitionMacro missing?

### ISSUE THREAD

**Issue by goderbauer** [jakemac53/macro_prototype#22]
The readme talks about a `ClassDefinitionMacro`, but it doesn't appear to be available as a class to implement.

**Comment by jakemac53** [comment]
I didn't implement this one because I don't think it actually makes sense to implement - I don't know what it would allow you to do :). You can implement the declarations in the class individually, but I don't know what it would mean to implement a class :).

If what you want to do is have a single class level annotation that can implement many declarations in the class, then one way to do that could be with https://github.com/jakemac53/macro_prototype/issues/8.

Or we could possibly make it such that a class definition macro can just directly operate on any declaration in the class.

**Comment by jakemac53** [comment]
Thinking more on this I think it is probably more intuitive for a `ClassDefinitionBuilder` to just be able to directly get a `FieldDefinitionBuilder` and/or `MethodDefinitionBuilder` for the declarations in the class, and then operate on those. That should also enable pretty good code re-use.

**Comment by jakemac53** [comment]
See https://github.com/dart-lang/language/blob/39bfd1f385470686d0f1b25d14289a6e7747d606/working/macros/api/builders.dart#L155
