### ISSUE TITLE
What is the purpose of `FunctionDefinitionMacro and where can I find use cases (example)?

### ISSUE THREAD

**Issue by mezoni** [jakemac53/macro_prototype#27]
What is the purpose of ``FunctionDefinitionMacro` and where can I find use cases (example)?

**Comment by jakemac53** [comment]
This macro allows you to fill in the body for an existing external/abstract function, in the _definition_ phase (last phase). It also allows you to wrap the body of a concrete function (one that already has an implementation) with additional code before or after the existing body. See the `FunctionDefinitionBuilder` api https://jakemac53.github.io/macro_prototype/doc/api/definition/FunctionDefinitionBuilder-class.html.

This is the same essentially as a `MethodDefinitionMacro` except it is for top level functions, instead of methods (which are associated with a class).

I don't have any existing examples in this repo but you could imagine any number of potential applications, for instance a type of serialization macro:

```dart
@serialize
external User decodeUser(Map<String, Object?> json);
```
